<?php

/**
 * @file
 * Main bdk_admin module file.
 */

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_field_widget_form_alter().
 */
function bdk_admin_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  if ($context['widget'] instanceof \Drupal\text\Plugin\Field\FieldWidget\TextareaWidget) {
    $element['#after_build'][] = '_allowed_formats_remove_textarea_help';
  }
}

/**
 * #after_build callback.
 */
function _allowed_formats_remove_textarea_help($form_element, FormStateInterface $form_state) {
  if (isset($form_element['format'])) {
    unset($form_element['format']['help']);
  }

  return $form_element;
}


///**
// * Implements hook_page_attachments().
// */
//function bdk_admin_page_attachments(array &$attachments) {
//  $theme = \Drupal::theme()->getActiveTheme()->getName();
//  if ($theme == 'claro') {
//    $attachments['#attached']['library'][] = 'bdk_admin/custom_styles';
//  }
//}

/**
 * Implements hook_theme().
 */
function bdk_admin_theme() {
  return [
    'bdk_admin_panel' => [
      'variables' => [
        'fields' => NULL,
      ],
      'template' => 'admin-panel',
    ],
  ];
}


