name: bardachok
recipe: drupal9
config:
  webroot: web
  xdebug: true
  config:
    php: php.ini
services:
  node:
    type: node:16
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
