<?php

/**
 * @file
 * Main bdk_register_overwrite module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element\PasswordConfirm;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bdk_register_overrides_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['account']['mail']['#attributes']['placeholder'] = 'Введите e-mail';
  $form['account']['mail']['#title'] = 'Ваш e-mail';
//  $form['account']['mail']['#required_error'] = 'Введите ваш e-mail';
//  $form['account']['mail']['#email_error'] = 'Введите ваш действительный e-mail';
  unset($form['account']['mail']['#description']);

  $form['account']['pass']['#process'][] = 'form_user_edit_process_pass';

  $form['policy_checkbox'] = [
    '#type' => 'checkbox',
    '#title' => 'Согласен с <a href="/test" target="_blank">политикой конфиденциальности</a>  и  <a href="/test" target="_blank">условиями использования</a>',
    '#required_error' => '',
    '#attributes' => [
      'id' => 'edit-policy-checkbox',
    ],
  ];
  $form['#validate'][] = 'form_validate';
}

/**
 * Process password fields.
 *
 * @param $element
 * @param FormStateInterface $form_state
 * @param $complete_form
 *
 * @return mixed
 */
function form_user_edit_process_pass(&$element, FormStateInterface $form_state, &$complete_form) {
  $element = PasswordConfirm::processPasswordConfirm($element, $form_state, $complete_form);
  $element['pass1']['#title'] = 'Ваш пароль';
  $element['pass1']['#attributes']['placeholder'] = 'Введите пароль';
//  $element['pass1']['#required_error'] = 'Введите ваш пароль';

  $element['pass2']['#title'] = 'Повторите пароль';
  $element['pass2']['#attributes']['placeholder'] = 'Введите пароль';
//  $element['pass2']['#required_error'] = 'Введите повторно ваш пароль';
  unset($element['#description']);
  return $element;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bdk_register_overrides_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['name']['#attributes']['placeholder'] = 'Введите e-mail';
  $form['name']['#title'] = 'Ваш e-mail';
  $form['name']['#required_error'] = 'Введите ваш e-mail';
  $form['name']['#email_error'] = 'Введите ваш действительный e-mail';
  unset($form['name']['#description']);

  $form['pass']['#attributes']['placeholder'] = 'Введите пароль';
  $form['pass']['#title'] = 'Ваш пароль';
  $form['pass']['#required_error'] = 'Введите ваш пароль';
  unset($form['pass']['#description']);
}

function form_validate($form, FormStateInterface $form_state) {
  if (!$form_state->getValue('policy_checkbox')) {
    $form_state->setErrorByName('policy_checkbox', 'Вы должны дать согласие.');
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function bdk_register_overrides_form_user_pass_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['name']['#attributes']['placeholder'] = 'Введите e-mail';
  $form['name']['#title'] = 'Ваш e-mail';
  $form['name']['#required_error'] = 'Введите ваш e-mail';
  $form['name']['#email_error'] = 'Введите ваш действительный e-mail';
  unset($form['mail']);
}
