<?php

/**
 * @file
 * Main bdk_search_block module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function bdk_search_block_theme() {
  return [
    'search_default_layout' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'search-default-layout',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Need to don't see the parameters 'form_build_id' and 'form_id' in the url
 * in order to make the search work.
 */
function bdk_search_block_form_search_mini_form_alter(&$form, FormStateInterface $form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}
